# Generated by Django 5.2.1 on 2025-06-09 15:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the document.', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Optional description or notes for the document.')),
                ('file', models.FileField(blank=True, help_text='Upload a file (e.g., PDF, image, spreadsheet).', null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the document was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the document was last updated.')),
                ('document_type', models.CharField(choices=[('PRIVATE', 'Private'), ('FAMILY_GROUP_SPECIFIC', 'Family Group Specific')], default='PRIVATE', help_text='Defines who can view this document (Private or Group Specific).', max_length=30)),
                ('created_by', models.ForeignKey(help_text='The user who created this document.', on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='The family group this document is associated with (if group specific).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='groups.familygroup')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
