# Generated by Django 5.2.1 on 2025-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_info',
            field=models.JSONField(blank=True, help_text='Additional contact details (phone, address, etc).', null=True, verbose_name='contact information'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('PLATFORM_ADMIN', 'Platform Admin')], default='USER', help_text="User's role on the platform.", max_length=20, verbose_name='user role'),
        ),
    ]
