# Generated by Django 5.2.1 on 2025-06-05 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('GROUP_SPECIFIC', 'Family Group Specific')], default='GROUP_SPECIFIC', help_text='Defines the audience/scope of the post.', max_length=20, verbose_name='post type')),
                ('content', models.TextField(help_text='The main text content of the post.', verbose_name='content')),
                ('media_attachments', models.JSONField(blank=True, default=list, help_text='JSON array of URLs to images or videos attached to the post.', null=True, verbose_name='media attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('visibility_settings', models.JSONField(blank=True, help_text='JSON for more granular visibility rules (e.g., specific members).', null=True, verbose_name='visibility settings')),
                ('last_edited_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last edited at')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='created by user')),
                ('group', models.ForeignKey(blank=True, help_text='The family group this post belongs to, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='groups.familygroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='liked at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
