# Generated by Django 5.2.1 on 2025-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('GROUP_SPECIFIC', 'Family Group Specific')], default='GROUP_SPECIFIC', help_text='Defines the audience/scope of the post.', max_length=20, verbose_name='post type'),
        ),
    ]
